### PR TITLE
FeedbackCommands should rely on elementId rather than element reference

### PR DESCRIPTION
**Pull request by CamilleLetavernier**
- Fix ModifyCssFeedbackCommand to use elementId rather than element reference

### CODE REVIEW

**Review by tortmayr — CHANGES_REQUESTED** [review]
Looks good to me.
However, I think it's better if we don't use direct element references in the action as well.
Otherwise subclassed/customized commands might use the element reference directly

**Comment by CamilleLetavernier** [comment]
Should we keep the element references in the constructor (And just assign that a string[] elementIds field?), or should we completely remove the SModelElements from the Action's constructor and use directly ids?

The first option would have less impact on existing clients, but is maybe a little bit less consistent

**Comment by tortmayr** [comment]
I'm fine with keeping the references in the constructor for now. I think we can life we the litte inconsistency and if needed we can easily fix this in a follow-up PR:

**Review by tortmayr — APPROVED** [review]
LGTM :+1:

**Pull request merged**
