### PR TITLE
GLSP-1096: Update to sprotty 0.14.0

### PR DESCRIPTION
**Pull request by tortmayr**
Update to sprotty 0.14.0 and adapt code to conform to latest changes/API breaks. With 0.14.0 the `ToolManager API` was deprecated and it will be removed in future versions. The intention is that this API moves to GLSP as it is only used there => refactor `ToolManager API`

Fixes https://github.com/eclipse-glsp/glsp/issues/1096 
Fixes https://github.com/eclipse-glsp/glsp/issues/1094 (via sprotty update)

### CODE REVIEW

**Comment by planger** [comment]
The code looks good, thank you!
However, I can't test this change. Maybe it is just me, but I think adaptations are missing for `@eclipse-glsp/theia-integration` after https://github.com/eclipse-glsp/glsp-client/pull/274 as I get build errors in `@eclipse-glsp/theia-integration`:
```
@eclipse-glsp/theia-integration: src/browser/diagram/features/export/theia-export-svg-action-handler.ts(45,53): error TS2551: Property 'getSourceUri' does not exist on type 'EditorContextService'. Did you mean 'sourceUri'?
@eclipse-glsp/theia-integration: src/browser/diagram/glsp-diagram-widget.ts(22,5): error TS2305: Module '"@eclipse-glsp/client"' has no exported member 'configureServerActions'.
@eclipse-glsp/theia-integration: src/browser/diagram/glsp-diagram-widget.ts(187,21): error TS2339: Property 'connect' does not exist on type 'GLSPModelSource'.
```

Or is there something wrong with my setup?
Thank you!

**Comment by tortmayr** [comment]
The integration projects have not been updated to the lastest clien state yet.
I have now opened a PR for the Theia integration (https://github.com/eclipse-glsp/glsp-theia-integration/pull/174).
The other projects are still pending. See also :https://github.com/eclipse-glsp/glsp/issues/960

**Comment by tortmayr** [comment]
@planger I rebased this PR on the latest master to resolve conflicts. Are there any open issues or can we go ahead and merge this?

**Comment by planger** [comment]
I think I still can't test this unfortunately, because I get the same build errors as in https://github.com/eclipse-glsp/glsp-theia-integration/pull/174 also with https://github.com/eclipse-glsp/glsp-theia-integration/pull/174.

**Comment by tortmayr** [comment]
Strange. It works fine for me.Nevertheless it's also fine to just test the
client change and then test this
integration change separately. We need to merge the client change
beforehand anyways.

**Review by planger — APPROVED** [review]
Ok, sounds reasonable! This change itself looks good to me. Thanks!

**Pull request merged**
