### PR TITLE
Add a reason for requesting and setting markers

### PR DESCRIPTION
**Pull request by planger**
Also track feedback by reason to replace only those on `SetMarkersAction` that have the same reason.

https://github.com/eclipse-glsp/glsp/issues/980

For review, please see [the comment on which changes belong together](https://github.com/eclipse-glsp/glsp/issues/980#issuecomment-1516867263).

### CODE REVIEW

**Review by tortmayr — CHANGES_REQUESTED** [review]
Thanks Philip, support for live validation is definitely a nice feature addition.
I did not have time to test the changes yet and only did a preliminary code review for now.

**Comment by planger** [comment]
Thank you for the excellent and quick review! I've applied your suggestions in 83e98974abba81fd76f6f50a0add5b2c9f1484e3

**Review by tortmayr — CHANGES_REQUESTED** [review]
The changes look good to me but looks like the tests are failing.
I guess the tests for `RequestMarkesActions`|`SetMarkersAction` in the protocol package need to be updated

**Review by tortmayr — APPROVED** [review]
LGTM! 👍🏼

**Pull request merged**
